events {}

http {
    server {
        listen 80;

        # Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend:5000/;
        }
    }
}
